APP=restlayer
WAR=$APP.war

IP=localhost
CONTAINER=$APP
REGISTRY=registry.ng.bluemix.net/mynodeappbue
PORT=9080
IMG=$APP

BX_IMG=$REGISTRY/$IMG
BX_IP=169.44.6.113
BX_CONTAINER_MEMORY=128
BX_PORT=$PORT