version: '2'
services:
  store:
    image: store-api:latest
    container_name: store
    environment:
      - DEBUG_PORT=7600
      - PORT=7700
      - APPLICATION_INSIGHTS_IKEY=${APPLICATION_INSIGHTS_IKEY}
    ports:
      - "7700:7700"
      - "7600:7600"
  solver:
    image: solver-api:latest
    container_name: solver
    environment:
      - DEBUG_PORT=7605
      - PORT=7705
      - STORE_URI=http://store:7700/store/task
      - BLOCKING_COEFFICIENT=0.1
      - APPLICATION_INSIGHTS_IKEY=${APPLICATION_INSIGHTS_IKEY}
    depends_on:
      - store
    links:
      - "store:store"
    ports:
      - "7705:7705"
      - "7605:7605"
  api:
    image: api:latest
    container_name: api
    environment:
      - DEBUG_PORT=7610
      - PORT=7710
      - STORE_URI=http://store:7700/store/task
      - SOLVER_URI=http://solver:7705/solver
      - APPLICATION_INSIGHTS_IKEY=${APPLICATION_INSIGHTS_IKEY}
    depends_on:
      - store
      - solver
    links:
      - "store:store"
      - "solver:solver"
    ports:
      - "7710:7710"
      - "7610:7610"