server:
  port: 7700
spring:
  application:
    name: store-api
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.HSQLDialect
      hibernate.show_sql: true
    hibernate:
      ddl-auto: create-drop

