server:
  port: ${PORT:7700}
spring:
  application:
    name: store-api
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.HSQLDialect
      hibernate.show_sql: false
    hibernate:
      ddl-auto: create-drop
azure:
  application-insights:
    instrumentation-key: ${APPLICATION_INSIGHTS_IKEY:idontknow}
