server:
<<<<<<< HEAD
  port: 8920
=======
  port: 7700
>>>>>>> substantial refactoring of services
logging:
  level:
    root: INFO
    org.hibernate:
      SQL: INFO
  file: store.log
spring:
  application:
    name: store-api
  datasource:
    username: sa
    url: jdbc:hsqldb:mem:test
    password:
    driver-class-name: org.hsqldb.jdbcDriver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.HSQLDialect
      hibernate.show_sql: true
    hibernate:
      ddl-auto: create-drop

