server:
  port: ${PORT:7710}
spring:
  application:
    name: api
org.aprestos.labs.apis.springboot2.uri:
  store: ${STORE_URI:http://store:7700/store/task}
  solver: ${SOLVER_URI:http://solver:7705/solver}
azure:
  application-insights:
    instrumentation-key: ${APPLICATION_INSIGHTS_IKEY:idontknow}




