version: '2'
services:
  store:
    image: caquicode/store-api:latest
    container_name: store
    environment:
      - DEBUG_PORT=7600
    ports:
      - "7700:7700"
      - "7600:7600"
  solver:
    image: caquicode/solver-api:latest
    container_name: solver
    environment:
      - DEBUG_PORT=7605
    depends_on:
      - store
    links:
      - "store:store"
    ports:
      - "7705:7705"
      - "7605:7605"
