server:
  port: ${PORT:7705}
spring:
  application:
    name: solver-api
org.aprestos.labs.apis.springboot2.solver:
  blocking-coefficient: ${BLOCKING_COEFFICIENT:0.0}
org.aprestos.labs.apis.springboot2.uri.store: ${STORE_URI:http://store:7700/store/task}
azure:
  application-insights:
    instrumentation-key: ${APPLICATION_INSIGHTS_IKEY:idontknow}